apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.extensions.example.com
spec:
  group: extensions.example.com
  names:
    kind: Website
    singular: website
    plural: websites
    shortNames:
      - ws
  scope: Namespaced
  version: v1